[versions]

kotlin = "1.9.22"

javaDiffUtils = "4.12"
junit = "5.9.2"
kotest = "5.5.5"
kotlinx-bcv = "0.13.1"
ow2Asm = "9.6"
dokka = "1.9.20"

gradlePluginPublishPlugin = "1.1.0"
androidGradlePlugin = "7.2.2"

[libraries]

## region Application libraries
kotlinx-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version = "2.0.0" }

javaDiffUtils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "javaDiffUtils" }

ow2-asm = { module = "org.ow2.asm:asm", version.ref = "ow2Asm" }
ow2-asmTree = { module = "org.ow2.asm:asm-tree", version.ref = "ow2Asm" }
## endregion


## region Test libraries
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

assertJ-core = { module = "org.assertj:assertj-core", version = "3.18.1" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
## endregion


## region Gradle Plugins
gradlePlugin-bcv = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinx-bcv" }
gradlePlugin-pluginPublishing = { module = "com.gradle.publish:plugin-publish-plugin", version.ref = "gradlePluginPublishPlugin" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
## endregion

[plugins]

kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.5" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
